// <auto-generated />
namespace vittigheder_web3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReferenceRemoval : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReferenceRemoval));
        
        string IMigrationMetadata.Id
        {
            get { return "201701071304072_ReferenceRemoval"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
